apiVersion: apps/v1
kind: Deployment
metadata:
  name: country-lookup-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: country-lookup-app
  template:
    metadata:
      labels:
        app: country-lookup-app
    spec:
      containers:
      - name: country-lookup-app
        image: country-lookup-app
        ports:
        - containerPort: 5000
